# kind: Service
# apiVersion: v1
# metadata:
#   name: nodeapp
# spec:
#   selector:
#     app: nodeapp
#   ports:
#   - protocol: TCP
#     port: 80
#     targetPort: 8080
#     nodePort: 30001 # Specify a node port within the minikube range
#   type: NodePort

apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nodejs-app
